<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <ImplicitAssemblyReferences>false</ImplicitAssemblyReferences>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AICalendar.Application\AICalendar.Application.csproj" />
    <ProjectReference Include="..\AICalendar.Infrastructure\AICalendar.Infrastructure.csproj" />
  </ItemGroup>
</Project>
